### PR TITLE
Add Bandit Nano as RX

### PR DESCRIPTION
**Pull request by IamPete1**
This adds a target for Bandit Nano as a receiver. Based on in instructions from @JyeSmith here https://discord.com/channels/596350022191415318/1165186741716656230/1167958708249186314

It uses the TX pad and the "SP" pin on the header for the bay adapter.

I was not able to get it working using the RX pad, any idea why that might be?

### CODE REVIEW

**Comment by IamPete1** [comment]
Updated to RX 3 and TX 1 following advice from V-22 (originally 13 and 17), https://discord.com/channels/596350022191415318/1165186741716656230/1216238191795900477

Now works on the provided pads.

**Comment by CapnBry** [comment]
I'm not sure we want to add "TX as RX" targets for every piece of hardware. The chance of a user seeing ".. Bandit Nano ... TX"  on the list and flashing their hardware with it, but it being not what they wanted and now their _module doesn't even work any more!_ is too much of an issue. Almost every piece of hardware is capable of being the other thing and would double the already overwhelming list size.

Maybe we can just have some sort of user wiki for posting hardware.json for RX as TX and TX as RX mods?

**Comment by IamPete1** [comment]
I understand the concern. It did take me a fair bit of messing about to get this working so it would be a same to loose it. Maybe a new "developer" or "advanced" field in `targets.json` that would hide it for most.

**Comment by JyeSmith** [comment]
I pushed a couple of commits to correct the LED and added a working button (middle press down on the joystick).

The Micro Bandit is also supported.  If a user has issues with the Micro and receiving TLM from the FC, try moving the Rx wire to the smaller pad on the rear.  The inline resistor (next to the pad) value appears to be too high on early versions. I think this was corrected on newer production runs.

image
image
image

**Comment by JyeSmith** [comment]
> I'm not sure we want to add "TX as RX" targets for every piece of hardware. The chance of a user seeing ".. Bandit Nano ... TX" on the list and flashing their hardware with it, but it being not what they wanted and now their _module doesn't even work any more!_ is too much of an issue. Almost every piece of hardware is capable of being the other thing and would double the already overwhelming list size.
> 
> Maybe we can just have some sort of user wiki for posting hardware.json for RX as TX and TX as RX mods?

These Tx modules were pushed for by the Dev to act as high power receivers.  And a number of users have actually been doing this recently.  We should support these properly.

**Review by pkendall64 — APPROVED** [review]
I'd like to find a better way to do this though.

i.e. have TX-as-RX settings in the RX Json file and perhaps have a "TX as RX" section in configurator/web-flasher in an advanced section.

**Review by wvarty — APPROVED** [review]
What Jye said.

This is where we have been directing our "power users" (pardon the pun) for high power TLM receivers. LGTM for now, and look at the improvements that PK suggested as future enhancements to support the cataloguing in configurator.

**Comment by CapnBry** [comment]
> These Tx modules were pushed for by the Dev to act as high power receivers. And a number of users have actually been doing this recently.

Sounds good to me too then oop it already happened in the night 😂

**Pull request merged**
