### PR TITLE
Add Unlock Higher Power for R9M Lite Pro

### PR DESCRIPTION
**Pull request by deadbytefpv**

### CODE REVIEW

**Review by pkendall64 — APPROVED** [review]

**Comment by neich03** [comment]
hi! i see that something is going on here... sorry my ignorance, but... how does this work? will be this implemented in the next Elrs configurator? infinite thanks for your awesome work!

**Comment by deadbytefpv** [comment]
> hi! i see that something is going on here... sorry my ignorance, but... how does this work? will be this implemented in the next Elrs configurator update? infinite thanks for your awesome work!

There should be no need for a new release just to get this into users.
We'll need to wait for other devs to have it reviewed. They can either approve it for merging or not.

The ExpressLRS Configurator could also use a big WARNING message when the option gets enabled, so users know the risks of having this option enabled.

**Comment by neich03** [comment]
perfect. thanks for the info!

**Comment by neich03** [comment]
Wow. Thank you so much guys. For all you do for the community♥️. Unbeleivable!🙌🏻🙏🏻

**Pull request merged**
